# Generated by Django 2.1.2 on 2018-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image_width',
            field=models.PositiveIntegerField(),
        ),
    ]
