# Generated by Django 2.1.2 on 2018-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_image', '0002_auto_20181020_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentimage',
            old_name='image_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='documentimage',
            old_name='image_width',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
