# Generated by Django 2.1.2 on 2018-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_image', '0003_auto_20181020_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentimage',
            old_name='height',
            new_name='image_height',
        ),
        migrations.RenameField(
            model_name='documentimage',
            old_name='width',
            new_name='image_width',
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='', width_field='image_width'),
        ),
    ]
